language: go
deploy:
  provider: gae
  keyfile: gae.json
  project: ifconfigme-186303
  on: production
before_install:
- openssl aes-256-cbc -K $encrypted_ba5c5be9ad49_key -iv $encrypted_ba5c5be9ad49_iv
  -in gae.json.enc -out gae.json -d
